name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # TODO: enable tests again when they are available
  # test:
  #   name: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '^1.20'
  #         check-latest: true
  #         cache-dependency-path: subdir/go.sum
  #     - name: Run tests
  #       run: go test ./...
  
  build-release:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: 'darwin'
            arch: 'amd64'
            cross: false
          - os: 'linux'
            arch: 'amd64'
            cross: false
          - os: 'linux'
            arch: 'arm64'
            cross: false
          - os: 'windows'
            arch: 'amd64'
            cross: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'
          check-latest: true
          cache-dependency-path: subdir/go.sum
          working-directory: src
      - name: Build for ${{ matrix.targets.os }} / ${{ matrix.targets.arch }}
        working-directory: src
        run: GOOS="${{ matrix.targets.os }}" GOARCH="${{ matrix.targets.arch }}" go build