name: build-release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Version of next deployment:"
        required: true

jobs:
  build-release:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: "darwin"
            arch: "amd64"
            cross: false
          - os: "linux"
            arch: "amd64"
            cross: false
          - os: "windows"
            arch: "amd64"
            cross: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.25"
          check-latest: true
          cache-dependency-path: subdir/go.sum
          working-directory: src
      - name: Set env var for executable output name
        shell: bash
        run: echo "OUTPUT_NAME=github-backup" >> $GITHUB_ENV
      - name: Build for ${{ matrix.targets.os }} / ${{ matrix.targets.arch }}
        working-directory: src
        run: GOOS="${{ matrix.targets.os }}" GOARCH="${{ matrix.targets.arch }}" go build -o ${{ env.OUTPUT_NAME }}
      - name: Set env var for executable (not windows)
        if: matrix.targets.os != 'windows'
        shell: bash
        run: echo "EXECUTABLE=${{ env.OUTPUT_NAME }}" >> $GITHUB_ENV
      - name: Set env var for executable and rename file (windows)
        if: matrix.targets.os == 'windows'
        shell: bash
        working-directory: src
        run: |
          echo "EXECUTABLE=${{ env.OUTPUT_NAME }}.exe" >> $GITHUB_ENV
          mv ${{ env.OUTPUT_NAME }} ${{ env.OUTPUT_NAME }}.exe
      - name: Set env var for zip file
        shell: bash
        run: echo "ZIPFILE=${{ env.OUTPUT_NAME }}-${{ matrix.targets.os }}-${{ matrix.targets.arch }}.zip" >> $GITHUB_ENV
      - name: Create artifactory ZIP
        shell: bash
        working-directory: src
        run: |
          zip ${{ env.ZIPFILE }} ${{ env.EXECUTABLE }}
      - name: Move file to artifact directory
        shell: bash
        run: |
          mkdir artifact
          mv src/${{ env.ZIPFILE }} artifact/
      - name: Save artifact
        uses: actions/upload-artifact@v6
        with:
          retention-days: 2
          name: artifact-${{ matrix.targets.os }}-${{ matrix.targets.arch }}
          path: artifact

  build-docker:
    name: build-docker
    runs-on: ubuntu-latest
    needs: [build-release]

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Get release artifacts from previous job
        uses: actions/download-artifact@v7
        with:
          name: artifact-linux-amd64
          path: artifact
      - name: Move file to docker build context
        shell: bash
        run: |
          unzip artifact/github-backup-linux-amd64.zip
          mv github-backup docker/github-backup
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: nextunit/github-backup
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/nextunit/github-backup
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  upload-release:
    name: upload-release
    runs-on: ubuntu-latest
    needs: [build-release]
    steps:
      - name: Generate the release version from tag
        if: env.RELEASE_VERSION == ''
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Output release version
        run: |
          echo "Release version: ${{ env.RELEASE_VERSION }}"
      - name: Get release artifacts from previous job
        uses: actions/download-artifact@v7
        with:
          path: artifact
          merge-multiple: true

      - name: Print out all release files
        run: |
          echo "Generated $(ls ./artifact | wc -l) files:"
          ls ./artifact
      - name: Upload all saved release files
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag_name: ${{ env.RELEASE_VERSION }}
          draft: true
          fail_on_unmatched_files: true
          name: ${{ env.RELEASE_VERSION }} Release
          body: |
            <!-- Write summary here -->
          files: |
            ./artifact/*
